/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/games/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Game State
     * @description Reconstrói a partida a partir da configuração e das ações já feitas.
     *
     *     Com ``actions`` vazio, inicia uma partida nova.
     */
    post: operations['game_state_api_games_state_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agent/decide': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Agent Decide
     * @description O agente lógico escolhe a próxima ação, que já é aplicada na resposta.
     */
    post: operations['agent_decide_api_agent_decide_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Action
     * @enum {string}
     */
    Action: 'turn_left' | 'turn_right' | 'forward' | 'grab' | 'shoot' | 'climb';
    /** AgentDecisionResponse */
    AgentDecisionResponse: {
      decision: components['schemas']['DecisionOut'];
      view: components['schemas']['GameView'];
    };
    /** AgentOut */
    AgentOut: {
      position: components['schemas']['PositionOut'];
      orientation: components['schemas']['Orientation'];
      /** Hasgold */
      hasGold: boolean;
      /** Hasarrow */
      hasArrow: boolean;
    };
    /** AskResultOut */
    AskResultOut: {
      position: components['schemas']['PositionOut'];
      /** Query */
      query: string;
      /** Entailed */
      entailed: boolean;
    };
    /**
     * BreezeMode
     * @enum {string}
     */
    BreezeMode: 'classic' | 'intensity';
    /** CellOut */
    CellOut: {
      position: components['schemas']['PositionOut'];
      /** Visited */
      visited: boolean;
      pit: components['schemas']['Truth'];
      wumpus: components['schemas']['Truth'];
      /** Safe */
      safe: boolean;
      /** @description Última percepção registrada na casa; só existe para casas visitadas. */
      percept: components['schemas']['PerceptOut'] | null;
    };
    /** DecisionOut */
    DecisionOut: {
      action: components['schemas']['Action'];
      /** Explanation */
      explanation: string;
      /** Plan */
      plan: components['schemas']['Action'][];
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Details */
      details?: string[];
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components['schemas']['ErrorBody'];
    };
    /** GameConfigIn */
    GameConfigIn: {
      /**
       * Size
       * @default 4
       */
      size: number;
      /**
       * Seed
       * @default 0
       */
      seed: number;
      /**
       * Pitprobability
       * @default 0.2
       */
      pitProbability: number;
      /** @default classic */
      breezeMode: components['schemas']['BreezeMode'];
      /** @default random */
      preset: components['schemas']['Preset'];
    };
    /**
     * GameEvent
     * @enum {string}
     */
    GameEvent:
      | 'turned'
      | 'moved'
      | 'bumped'
      | 'fell_into_pit'
      | 'eaten_by_wumpus'
      | 'grabbed_gold'
      | 'nothing_to_grab'
      | 'shot_hit'
      | 'shot_missed'
      | 'no_arrow'
      | 'climbed_with_gold'
      | 'climbed_without_gold'
      | 'cannot_climb';
    /** GameRequest */
    GameRequest: {
      config: components['schemas']['GameConfigIn'];
      /** Actions */
      actions?: components['schemas']['Action'][];
    };
    /**
     * GameStatus
     * @enum {string}
     */
    GameStatus: 'playing' | 'won' | 'escaped' | 'dead';
    /** GameView */
    GameView: {
      config: components['schemas']['GameConfigIn'];
      status: components['schemas']['GameStatus'];
      /** Score */
      score: number;
      /** Step */
      step: number;
      agent: components['schemas']['AgentOut'];
      percept: components['schemas']['PerceptOut'];
      /** Events */
      events: components['schemas']['GameEvent'][];
      /**
       * Wumpusdeadknown
       * @description A KB prova que o Wumpus está morto.
       */
      wumpusDeadKnown: boolean;
      /** Cells */
      cells: components['schemas']['CellOut'][];
      knowledgeBase: components['schemas']['KnowledgeBaseOut'];
      /** Queries */
      queries: components['schemas']['AskResultOut'][];
      pitModels: components['schemas']['PitModelsOut'];
      /** @description Mundo real, revelado só quando a partida termina. */
      world: components['schemas']['WorldOut'] | null;
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok';
    };
    /** KbEntryOut */
    KbEntryOut: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Description */
      description: string;
      origin: components['schemas']['Origin'];
      /** Step */
      step: number;
      /** Clausecount */
      clauseCount: number;
    };
    /** KbStatsOut */
    KbStatsOut: {
      /** Sentences */
      sentences: number;
      /** Clauses */
      clauses: number;
      /** Symbols */
      symbols: number;
    };
    /** KnowledgeBaseOut */
    KnowledgeBaseOut: {
      /** Entries */
      entries: components['schemas']['KbEntryOut'][];
      stats: components['schemas']['KbStatsOut'];
    };
    /**
     * Orientation
     * @enum {string}
     */
    Orientation: 'north' | 'east' | 'south' | 'west';
    /**
     * Origin
     * @enum {string}
     */
    Origin: 'rule' | 'percept' | 'action';
    /** PerceptOut */
    PerceptOut: {
      /** Stench */
      stench: boolean;
      /** Breeze */
      breeze: number;
      /** Glitter */
      glitter: boolean;
      /** Bump */
      bump: boolean;
      /** Scream */
      scream: boolean;
    };
    /** PitModelsOut */
    PitModelsOut: {
      /** Symbols */
      symbols: string[];
      /** Totalassignments */
      totalAssignments: number;
      /** Modelcount */
      modelCount: number;
      /** Models */
      models: {
        [key: string]: boolean;
      }[];
      /** Truncated */
      truncated: boolean;
      /** Skipped */
      skipped: boolean;
    };
    /** PositionOut */
    PositionOut: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /**
     * Preset
     * @enum {string}
     */
    Preset: 'random' | 'slides';
    /**
     * Truth
     * @enum {string}
     */
    Truth: 'yes' | 'no' | 'unknown';
    /** WorldOut */
    WorldOut: {
      wumpus: components['schemas']['PositionOut'];
      gold: components['schemas']['PositionOut'];
      /** Pits */
      pits: components['schemas']['PositionOut'][];
      /** Wumpusalive */
      wumpusAlive: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  game_state_api_games_state_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GameRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameView'];
        };
      };
      /** @description A partida já terminou. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Requisição inválida. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  agent_decide_api_agent_decide_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GameRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentDecisionResponse'];
        };
      };
      /** @description A partida já terminou. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Requisição inválida. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
